/*
 * Generated by Bluespec Compiler, version 2023.07-15-g10e1952c (build 10e1952c)
 * 
 * On Tue Oct 31 11:00:33 CST 2023
 * 
 */
#include "bluesim_primitives.h"
#include "mkTbCSA.h"
#include "imported_BDPI_functions.h"


/* String declarations */
static std::string const __str_literal_2("FAILED %d + %d gave %d instead of %d", 36u);
static std::string const __str_literal_1("PASSED", 6u);


/* Constructor */
MOD_mkTbCSA::MOD_mkTbCSA(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_cycle(simHdl, "cycle", this, 32u, 0u, (tUInt8)0u),
    INST_randomVal1_ignore(simHdl, "randomVal1_ignore", this, 8u, (tUInt8)0u),
    INST_randomVal1_initialized(simHdl, "randomVal1_initialized", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_randomVal1_zaz(simHdl, "randomVal1_zaz", this, 8u, (tUInt8)0u),
    INST_randomVal2_ignore(simHdl, "randomVal2_ignore", this, 8u, (tUInt8)0u),
    INST_randomVal2_initialized(simHdl, "randomVal2_initialized", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_randomVal2_zaz(simHdl, "randomVal2_zaz", this, 8u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u),
    DEF_v__h691(2863311530u),
    DEF_v__h315(2863311530u)
{
  symbol_count = 13u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkTbCSA::init_symbols_0()
{
  init_symbol(&symbols[0u], "cycle", SYM_MODULE, &INST_cycle);
  init_symbol(&symbols[1u], "RL_randomVal1_every", SYM_RULE);
  init_symbol(&symbols[2u], "RL_randomVal1_every_1", SYM_RULE);
  init_symbol(&symbols[3u], "RL_randomVal2_every", SYM_RULE);
  init_symbol(&symbols[4u], "RL_randomVal2_every_1", SYM_RULE);
  init_symbol(&symbols[5u], "RL_test", SYM_RULE);
  init_symbol(&symbols[6u], "randomVal1_ignore", SYM_MODULE, &INST_randomVal1_ignore);
  init_symbol(&symbols[7u], "randomVal1_initialized", SYM_MODULE, &INST_randomVal1_initialized);
  init_symbol(&symbols[8u], "randomVal1_zaz", SYM_MODULE, &INST_randomVal1_zaz);
  init_symbol(&symbols[9u], "randomVal2_ignore", SYM_MODULE, &INST_randomVal2_ignore);
  init_symbol(&symbols[10u], "randomVal2_initialized", SYM_MODULE, &INST_randomVal2_initialized);
  init_symbol(&symbols[11u], "randomVal2_zaz", SYM_MODULE, &INST_randomVal2_zaz);
  init_symbol(&symbols[12u], "x__h945", SYM_DEF, &DEF_x__h945, 32u);
}


/* Rule actions */

void MOD_mkTbCSA::RL_randomVal1_every()
{
  tUInt8 DEF_new_value__h357;
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h315 = rand32();
  DEF_new_value__h357 = (tUInt8)((tUInt8)255u & DEF_v__h315);
  INST_randomVal1_zaz.METH_wset(DEF_new_value__h357);
}

void MOD_mkTbCSA::RL_randomVal1_every_1()
{
  DEF_x_wget__h250 = INST_randomVal1_zaz.METH_wget();
  DEF_v__h389 = INST_randomVal1_zaz.METH_whas() ? DEF_x_wget__h250 : (tUInt8)0u;
  INST_randomVal1_ignore.METH_wset(DEF_v__h389);
}

void MOD_mkTbCSA::RL_randomVal2_every()
{
  tUInt8 DEF_new_value__h733;
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h691 = rand32();
  DEF_new_value__h733 = (tUInt8)((tUInt8)255u & DEF_v__h691);
  INST_randomVal2_zaz.METH_wset(DEF_new_value__h733);
}

void MOD_mkTbCSA::RL_randomVal2_every_1()
{
  DEF_x_wget__h634 = INST_randomVal2_zaz.METH_wget();
  DEF_v__h764 = INST_randomVal2_zaz.METH_whas() ? DEF_x_wget__h634 : (tUInt8)0u;
  INST_randomVal2_ignore.METH_wset(DEF_v__h764);
}

void MOD_mkTbCSA::RL_test()
{
  tUInt8 DEF_high__h1138;
  tUInt32 DEF_x__h2575;
  tUInt8 DEF_y__h1577;
  tUInt8 DEF_x__h1576;
  tUInt8 DEF_y__h1677;
  tUInt8 DEF_y__h1741;
  tUInt8 DEF_x__h1740;
  tUInt8 DEF_y__h1739;
  tUInt8 DEF_x__h1738;
  tUInt8 DEF_y__h1679;
  tUInt8 DEF_x__h1678;
  tUInt8 DEF_x__h1676;
  tUInt8 DEF_y__h1575;
  tUInt8 DEF_x__h1574;
  tUInt8 DEF_y__h1445;
  tUInt8 DEF_x__h1444;
  tUInt8 DEF_y__h1443;
  tUInt8 DEF_x__h1442;
  tUInt8 DEF_y__h1383;
  tUInt8 DEF_x__h1382;
  tUInt8 DEF_y__h1381;
  tUInt8 DEF_x__h1380;
  tUInt8 DEF_y__h1321;
  tUInt8 DEF_x__h1320;
  tUInt8 DEF_y__h1319;
  tUInt8 DEF_x__h1318;
  tUInt8 DEF_y__h1213;
  tUInt8 DEF_x__h1212;
  tUInt8 DEF_y__h1211;
  tUInt8 DEF_x__h1210;
  tUInt8 DEF__theResult___fst__h1147;
  tUInt8 DEF_c__h1199;
  tUInt8 DEF_x__h2210;
  tUInt8 DEF_c__h1307;
  tUInt8 DEF_x__h2266;
  tUInt8 DEF_c__h1369;
  tUInt8 DEF_x__h2322;
  tUInt8 DEF_c__h1431;
  tUInt8 DEF_x__h2378;
  tUInt8 DEF_c__h1563;
  tUInt8 DEF_x__h1922;
  tUInt8 DEF_c__h1665;
  tUInt8 DEF_x__h1978;
  tUInt8 DEF_c__h1727;
  tUInt8 DEF_x__h2034;
  tUInt8 DEF_NOT_cycle_5_EQ_0_6_1_AND_NOT_cycle_5_EQ_128_7__ETC___d100;
  tUInt32 DEF_realAns__h2446;
  tUInt32 DEF_v__h1133;
  tUInt8 DEF_b__h1788;
  tUInt8 DEF_b__h1726;
  tUInt8 DEF_b__h1664;
  tUInt8 DEF_b__h1562;
  tUInt8 DEF_b__h1430;
  tUInt8 DEF_b__h1368;
  tUInt8 DEF_b__h1306;
  tUInt8 DEF_b__h1198;
  tUInt8 DEF_a__h1787;
  tUInt8 DEF_a__h1725;
  tUInt8 DEF_a__h1663;
  tUInt8 DEF_a__h1561;
  tUInt8 DEF_a__h1429;
  tUInt8 DEF_a__h1367;
  tUInt8 DEF_a__h1305;
  tUInt8 DEF_a__h1197;
  DEF_x__h945 = INST_cycle.METH_read();
  DEF_x_wget__h634 = INST_randomVal2_zaz.METH_wget();
  DEF_x_wget__h250 = INST_randomVal1_zaz.METH_wget();
  DEF_v__h389 = INST_randomVal1_zaz.METH_whas() ? DEF_x_wget__h250 : (tUInt8)0u;
  DEF_a__h1197 = (tUInt8)(DEF_v__h389 >> 7u);
  DEF_a__h1305 = (tUInt8)((tUInt8)1u & (DEF_v__h389 >> 6u));
  DEF_a__h1367 = (tUInt8)((tUInt8)1u & (DEF_v__h389 >> 5u));
  DEF_a__h1429 = (tUInt8)((tUInt8)1u & (DEF_v__h389 >> 4u));
  DEF_a__h1561 = (tUInt8)((tUInt8)1u & (DEF_v__h389 >> 3u));
  DEF_a__h1663 = (tUInt8)((tUInt8)1u & (DEF_v__h389 >> 2u));
  DEF_a__h1725 = (tUInt8)((tUInt8)1u & (DEF_v__h389 >> 1u));
  DEF_a__h1787 = (tUInt8)((tUInt8)1u & DEF_v__h389);
  DEF_v__h764 = INST_randomVal2_zaz.METH_whas() ? DEF_x_wget__h634 : (tUInt8)0u;
  DEF_b__h1198 = (tUInt8)(DEF_v__h764 >> 7u);
  DEF_b__h1306 = (tUInt8)((tUInt8)1u & (DEF_v__h764 >> 6u));
  DEF_b__h1368 = (tUInt8)((tUInt8)1u & (DEF_v__h764 >> 5u));
  DEF_b__h1430 = (tUInt8)((tUInt8)1u & (DEF_v__h764 >> 4u));
  DEF_b__h1562 = (tUInt8)((tUInt8)1u & (DEF_v__h764 >> 3u));
  DEF_b__h1664 = (tUInt8)((tUInt8)1u & (DEF_v__h764 >> 2u));
  DEF_b__h1726 = (tUInt8)((tUInt8)1u & (DEF_v__h764 >> 1u));
  DEF_b__h1788 = (tUInt8)((tUInt8)1u & DEF_v__h764);
  DEF_cycle_5_EQ_128___d17 = DEF_x__h945 == 128u;
  DEF_cycle_5_EQ_0___d16 = DEF_x__h945 == 0u;
  DEF_realAns__h2446 = 511u & ((511u & ((((tUInt32)((tUInt8)0u)) << 8u) | (tUInt32)(DEF_v__h389))) + (511u & ((((tUInt32)((tUInt8)0u)) << 8u) | (tUInt32)(DEF_v__h764))));
  DEF_x__h2034 = DEF_a__h1725 ^ DEF_b__h1726;
  DEF_x__h1978 = DEF_a__h1663 ^ DEF_b__h1664;
  DEF_c__h1727 = DEF_a__h1787 & DEF_b__h1788;
  DEF_x__h1922 = DEF_a__h1561 ^ DEF_b__h1562;
  DEF_x__h2378 = DEF_a__h1429 ^ DEF_b__h1430;
  DEF_x__h2266 = DEF_a__h1305 ^ DEF_b__h1306;
  DEF_x__h2322 = DEF_a__h1367 ^ DEF_b__h1368;
  DEF_x__h2210 = DEF_a__h1197 ^ DEF_b__h1198;
  DEF_x__h1212 = DEF_a__h1197 & DEF_b__h1198;
  DEF_x__h1320 = DEF_a__h1305 & DEF_b__h1306;
  DEF_x__h1382 = DEF_a__h1367 & DEF_b__h1368;
  DEF_x__h1444 = DEF_a__h1429 & DEF_b__h1430;
  DEF_x__h1678 = DEF_a__h1663 & DEF_b__h1664;
  DEF_y__h1739 = DEF_b__h1726 & DEF_c__h1727;
  DEF_x__h2575 = DEF_x__h945 + 1u;
  DEF_x__h1740 = DEF_a__h1725 & DEF_b__h1726;
  DEF_y__h1741 = DEF_a__h1725 & DEF_c__h1727;
  DEF_x__h1738 = DEF_x__h1740 | DEF_y__h1741;
  DEF_c__h1665 = DEF_x__h1738 | DEF_y__h1739;
  DEF_y__h1679 = DEF_a__h1663 & DEF_c__h1665;
  DEF_x__h1676 = DEF_x__h1678 | DEF_y__h1679;
  DEF_y__h1677 = DEF_b__h1664 & DEF_c__h1665;
  DEF_c__h1563 = DEF_x__h1676 | DEF_y__h1677;
  DEF_y__h1575 = DEF_b__h1562 & DEF_c__h1563;
  DEF_x__h1576 = DEF_a__h1561 & DEF_b__h1562;
  DEF_y__h1577 = DEF_a__h1561 & DEF_c__h1563;
  DEF_x__h1574 = DEF_x__h1576 | DEF_y__h1577;
  DEF_c__h1431 = DEF_x__h1574 | DEF_y__h1575;
  DEF_y__h1443 = DEF_b__h1430 & DEF_c__h1431;
  DEF_y__h1445 = DEF_a__h1429 & DEF_c__h1431;
  DEF_x__h1442 = DEF_x__h1444 | DEF_y__h1445;
  DEF_c__h1369 = DEF_x__h1442 | DEF_y__h1443;
  DEF_y__h1381 = DEF_b__h1368 & DEF_c__h1369;
  DEF_y__h1383 = DEF_a__h1367 & DEF_c__h1369;
  DEF_x__h1380 = DEF_x__h1382 | DEF_y__h1383;
  DEF_c__h1307 = DEF_x__h1380 | DEF_y__h1381;
  DEF_y__h1319 = DEF_b__h1306 & DEF_c__h1307;
  DEF_y__h1321 = DEF_a__h1305 & DEF_c__h1307;
  DEF_x__h1318 = DEF_x__h1320 | DEF_y__h1321;
  DEF_c__h1199 = DEF_x__h1318 | DEF_y__h1319;
  DEF_y__h1211 = DEF_b__h1198 & DEF_c__h1199;
  DEF_y__h1213 = DEF_a__h1197 & DEF_c__h1199;
  DEF_x__h1210 = DEF_x__h1212 | DEF_y__h1213;
  DEF__theResult___fst__h1147 = DEF_x__h1210 | DEF_y__h1211;
  DEF_high__h1138 = (tUInt8)31u & (((((DEF__theResult___fst__h1147 << 4u) | ((DEF_x__h2210 ^ DEF_c__h1199) << 3u)) | ((DEF_x__h2266 ^ DEF_c__h1307) << 2u)) | ((DEF_x__h2322 ^ DEF_c__h1369) << 1u)) | (DEF_x__h2378 ^ DEF_c__h1431));
  DEF_v__h1133 = 511u & (((((((tUInt32)(DEF_high__h1138)) << 4u) | (((tUInt32)(DEF_x__h1922 ^ DEF_c__h1563)) << 3u)) | (((tUInt32)(DEF_x__h1978 ^ DEF_c__h1665)) << 2u)) | (((tUInt32)(DEF_x__h2034 ^ DEF_c__h1727)) << 1u)) | (tUInt32)(DEF_a__h1787 ^ DEF_b__h1788));
  DEF_NOT_cycle_5_EQ_0_6_1_AND_NOT_cycle_5_EQ_128_7__ETC___d100 = !DEF_cycle_5_EQ_0___d16 && (!DEF_cycle_5_EQ_128___d17 && !(DEF_v__h1133 == DEF_realAns__h2446));
  if (DEF_cycle_5_EQ_0___d16)
    INST_randomVal1_initialized.METH_write((tUInt8)1u);
  if (DEF_cycle_5_EQ_0___d16)
    INST_randomVal2_initialized.METH_write((tUInt8)1u);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_cycle_5_EQ_128___d17)
      dollar_display(sim_hdl, this, "s", &__str_literal_1);
    if (DEF_cycle_5_EQ_128___d17)
      dollar_finish(sim_hdl, "32", 1u);
    if (DEF_NOT_cycle_5_EQ_0_6_1_AND_NOT_cycle_5_EQ_128_7__ETC___d100)
      dollar_display(sim_hdl,
		     this,
		     "s,8,8,9,9",
		     &__str_literal_2,
		     DEF_v__h389,
		     DEF_v__h764,
		     DEF_v__h1133,
		     DEF_realAns__h2446);
    if (DEF_NOT_cycle_5_EQ_0_6_1_AND_NOT_cycle_5_EQ_128_7__ETC___d100)
      dollar_finish(sim_hdl, "32", 1u);
  }
  INST_cycle.METH_write(DEF_x__h2575);
}


/* Methods */


/* Reset routines */

void MOD_mkTbCSA::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_randomVal2_initialized.reset_RST(ARG_rst_in);
  INST_randomVal1_initialized.reset_RST(ARG_rst_in);
  INST_cycle.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkTbCSA::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkTbCSA::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_cycle.dump_state(indent + 2u);
  INST_randomVal1_ignore.dump_state(indent + 2u);
  INST_randomVal1_initialized.dump_state(indent + 2u);
  INST_randomVal1_zaz.dump_state(indent + 2u);
  INST_randomVal2_ignore.dump_state(indent + 2u);
  INST_randomVal2_initialized.dump_state(indent + 2u);
  INST_randomVal2_zaz.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkTbCSA::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 17u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "cycle_5_EQ_0___d16", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "cycle_5_EQ_128___d17", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h315", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h389", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h691", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h764", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h945", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h250", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h634", 8u);
  num = INST_cycle.dump_VCD_defs(num);
  num = INST_randomVal1_ignore.dump_VCD_defs(num);
  num = INST_randomVal1_initialized.dump_VCD_defs(num);
  num = INST_randomVal1_zaz.dump_VCD_defs(num);
  num = INST_randomVal2_ignore.dump_VCD_defs(num);
  num = INST_randomVal2_initialized.dump_VCD_defs(num);
  num = INST_randomVal2_zaz.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkTbCSA::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTbCSA &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkTbCSA::vcd_defs(tVCDDumpType dt, MOD_mkTbCSA &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 8u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_cycle_5_EQ_0___d16) != DEF_cycle_5_EQ_0___d16)
      {
	vcd_write_val(sim_hdl, num, DEF_cycle_5_EQ_0___d16, 1u);
	backing.DEF_cycle_5_EQ_0___d16 = DEF_cycle_5_EQ_0___d16;
      }
      ++num;
      if ((backing.DEF_cycle_5_EQ_128___d17) != DEF_cycle_5_EQ_128___d17)
      {
	vcd_write_val(sim_hdl, num, DEF_cycle_5_EQ_128___d17, 1u);
	backing.DEF_cycle_5_EQ_128___d17 = DEF_cycle_5_EQ_128___d17;
      }
      ++num;
      if ((backing.DEF_v__h315) != DEF_v__h315)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h315, 32u);
	backing.DEF_v__h315 = DEF_v__h315;
      }
      ++num;
      if ((backing.DEF_v__h389) != DEF_v__h389)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h389, 8u);
	backing.DEF_v__h389 = DEF_v__h389;
      }
      ++num;
      if ((backing.DEF_v__h691) != DEF_v__h691)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h691, 32u);
	backing.DEF_v__h691 = DEF_v__h691;
      }
      ++num;
      if ((backing.DEF_v__h764) != DEF_v__h764)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h764, 8u);
	backing.DEF_v__h764 = DEF_v__h764;
      }
      ++num;
      if ((backing.DEF_x__h945) != DEF_x__h945)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h945, 32u);
	backing.DEF_x__h945 = DEF_x__h945;
      }
      ++num;
      if ((backing.DEF_x_wget__h250) != DEF_x_wget__h250)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h250, 8u);
	backing.DEF_x_wget__h250 = DEF_x_wget__h250;
      }
      ++num;
      if ((backing.DEF_x_wget__h634) != DEF_x_wget__h634)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h634, 8u);
	backing.DEF_x_wget__h634 = DEF_x_wget__h634;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_cycle_5_EQ_0___d16, 1u);
      backing.DEF_cycle_5_EQ_0___d16 = DEF_cycle_5_EQ_0___d16;
      vcd_write_val(sim_hdl, num++, DEF_cycle_5_EQ_128___d17, 1u);
      backing.DEF_cycle_5_EQ_128___d17 = DEF_cycle_5_EQ_128___d17;
      vcd_write_val(sim_hdl, num++, DEF_v__h315, 32u);
      backing.DEF_v__h315 = DEF_v__h315;
      vcd_write_val(sim_hdl, num++, DEF_v__h389, 8u);
      backing.DEF_v__h389 = DEF_v__h389;
      vcd_write_val(sim_hdl, num++, DEF_v__h691, 32u);
      backing.DEF_v__h691 = DEF_v__h691;
      vcd_write_val(sim_hdl, num++, DEF_v__h764, 8u);
      backing.DEF_v__h764 = DEF_v__h764;
      vcd_write_val(sim_hdl, num++, DEF_x__h945, 32u);
      backing.DEF_x__h945 = DEF_x__h945;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h250, 8u);
      backing.DEF_x_wget__h250 = DEF_x_wget__h250;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h634, 8u);
      backing.DEF_x_wget__h634 = DEF_x_wget__h634;
    }
}

void MOD_mkTbCSA::vcd_prims(tVCDDumpType dt, MOD_mkTbCSA &backing)
{
  INST_cycle.dump_VCD(dt, backing.INST_cycle);
  INST_randomVal1_ignore.dump_VCD(dt, backing.INST_randomVal1_ignore);
  INST_randomVal1_initialized.dump_VCD(dt, backing.INST_randomVal1_initialized);
  INST_randomVal1_zaz.dump_VCD(dt, backing.INST_randomVal1_zaz);
  INST_randomVal2_ignore.dump_VCD(dt, backing.INST_randomVal2_ignore);
  INST_randomVal2_initialized.dump_VCD(dt, backing.INST_randomVal2_initialized);
  INST_randomVal2_zaz.dump_VCD(dt, backing.INST_randomVal2_zaz);
}
